@startuml
skinparam actorStyle Hollow
left to right direction

:Eleve: as EL
:Mentor: as Mento
:Utilisateur: as U

Mento --> U
EL --> U

package "Website Learn@home" {
    rectangle "Page de connexion" {
        (S'authentifier) as ID
        U --> ID
    }
    rectangle "Tableau de bord" {
        (S'informer \n sur les autres activites) as S
        U --> S
    }
    rectangle "Chat" {
        (Communiquer\nde facon instantanee) as C
        U --> C
    }
    rectangle "Gestionnaire de taches" {
        (Gerer ses taches) as T
        U --> T
    }
    rectangle "Calendrier" {
        (Gerer ses rendez-vous) as G
        U --> G
    }
}

@enduml